### ISSUE TITLE
Problem with newer webpack modules

### ISSUE THREAD

**Issue by 0xlord** [Dahlgren/arma-server-web-admin#131]
Hello,

Want to test out your web admin tool. I set up a JSNode environment and downloaded all the required files. For reference, this is our `config.js`:
```module.exports = {
  game: 'arma3', // arma3, arma2oa, arma2, arma1, cwa, ofpresistance, ofp
  path: 'C:\\arma_eu4_building',
  port: 44772,
  host: 'xyz', // Can be either an IP or a Hostname
  type: 'windows', // Can be either linux, windows or wine
  parameters: [ // Additional startup parameters used by all servers
    '-noSound',
    '-world=empty'
  ],
  serverMods: [ // Mods used exclusively by server and not shared with clients
    // '@mod1',
    // '@mod2',
  ],
  admins: [], // add steam IDs here to enable #login without password
  auth: { // If both username and password is set, HTTP Basic Auth will be used. You may use an array to specify more than one user.
    username: 'xyz', // Username for HTTP Basic Auth
    password: 'xyz', // Password for HTTP Basic Auth
  },
  prefix: "", // Prefix to all server names
  suffix: "", // Suffix to all server names
  logFormat: "dev", // expressjs/morgan log format
};
```
It is configured with a public IP, username is set with Upper/Lower Case, Numbers and a Underscore, Password has Upper/Lower/Number/Symbols/Brackets.

When I use `npm start` I will get this error message:

```
PS C:\Arma-WebAdmin> npm start

> arma-server-web-admin@0.0.1 start C:\Arma-WebAdmin
> node app.js

C:\Arma-WebAdmin\node_modules\webpack\lib\webpack.js:23
                throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
                ^

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'loaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, noParse?, rules?, defaultRules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknown
ContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp?, strictExportPresence?, strictThisContextOnImports? }
   -> Options affecting the normal modules (`NormalModuleFactory`).
    at webpack (C:\Arma-WebAdmin\node_modules\webpack\lib\webpack.js:23:9)
    at Object.<anonymous> (C:\Arma-WebAdmin\app.js:22:23)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)
    at startMainThreadExecution (internal/bootstrap/node.js:439:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! arma-server-web-admin@0.0.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the arma-server-web-admin@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-01-28T16_13_39_037Z-debug.log
PS C:\Arma-WebAdmin>
```

According to [some StackOverflow threads](https://stackoverflow.com/questions/49370849/configuration-module-has-an-unknown-property-loaders) you need to change `loaders` to `rules` since `webhook@4.0.0`. When I do this on line 44 of `webpack.config.js`, then I see this error message:

```
PS C:\Arma-WebAdmin> npm start

> arma-server-web-admin@0.0.1 start C:\Arma-WebAdmin
> node app.js

Could not load any existing servers configuration, starting fresh
(node:9976) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
× ｢wdm｣: Hash: cbc31d75ce9463d624d8
Version: webpack 4.0.0
Time: 2407ms
Built at: 1/28/2019 5:15:15 PM
      Asset      Size  Chunks  Chunk Names
0.bundle.js  1.91 MiB       0
1.bundle.js   163 KiB       1
  bundle.js   483 KiB       2  main
Entrypoint main = bundle.js
   [0] ./node_modules/style-loader/addStyles.js 6.99 KiB {2} [built]
   [2] ./node_modules/sweetalert/dist/sweetalert.css 874 bytes {2} [built]
   [4] ./node_modules/css-loader!./public/css/styles.css 391 bytes {2} [built]
   [5] ./public/css/styles.css 914 bytes {2} [built]
   [6] ./node_modules/css-loader!./node_modules/sweetalert/dist/sweetalert.css 23.4 KiB {2} [built]
   [7] ./node_modules/css-loader!./node_modules/ladda/dist/ladda-themeless.min.css 7.84 KiB {2} [built]
   [8] ./node_modules/ladda/dist/ladda-themeless.min.css 901 bytes {2} [built]
  [13] ./node_modules/css-loader!./node_modules/bootstrap/dist/css/bootstrap.css 150 KiB {2} [built]
  [14] ./node_modules/bootstrap/dist/css/bootstrap.css 883 bytes {2} [built]
  [15] ./public/js/app.js 1.02 KiB {2} [built]
  [16] ./node_modules/jquery/dist/jquery.js 265 KiB {0} [built]
  [17] ./node_modules/backbone/backbone.js 70.5 KiB {0} [built]
  [18] ./public/js/app/router.js 2.57 KiB {1} [built]
  [19] ./node_modules/bootstrap/dist/js/npm.js 484 bytes {0} [built]
  [20] ./node_modules/underscore/underscore.js 56.9 KiB {0} [built]
    + 111 hidden modules

WARNING in configuration
The 'mode' option has not been set. Set 'mode' option to 'development' or 'production' to enable defaults for this environment.

ERROR in ./node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.eot
Module build failed: TypeError: Cannot read property 'fileLoader' of undefined
    at Object.module.exports (C:\Arma-WebAdmin\node_modules\file-loader\index.js:13:28)
 @ ./node_modules/css-loader!./node_modules/bootstrap/dist/css/bootstrap.css 6:4558-4610 6:4633-4685
 @ ./node_modules/bootstrap/dist/css/bootstrap.css
 @ ./public/js/app.js

ERROR in ./node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.woff
Module build failed: TypeError: Cannot read property 'fileLoader' of undefined
    at Object.module.exports (C:\Arma-WebAdmin\node_modules\file-loader\index.js:13:28)
    at Object.loader (C:\Arma-WebAdmin\node_modules\url-loader\dist\index.js:76:19)
 @ ./node_modules/css-loader!./node_modules/bootstrap/dist/css/bootstrap.css 6:4824-4877
 @ ./node_modules/bootstrap/dist/css/bootstrap.css
 @ ./public/js/app.js

ERROR in ./node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2
Module build failed: TypeError: Cannot read property 'fileLoader' of undefined
    at Object.module.exports (C:\Arma-WebAdmin\node_modules\file-loader\index.js:13:28)
    at Object.loader (C:\Arma-WebAdmin\node_modules\url-loader\dist\index.js:76:19)
 @ ./node_modules/css-loader!./node_modules/bootstrap/dist/css/bootstrap.css 6:4737-4791
 @ ./node_modules/bootstrap/dist/css/bootstrap.css
 @ ./public/js/app.js

ERROR in ./node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
Module build failed: TypeError: Cannot read property 'fileLoader' of undefined
    at Object.module.exports (C:\Arma-WebAdmin\node_modules\file-loader\index.js:13:28)
    at Object.loader (C:\Arma-WebAdmin\node_modules\url-loader\dist\index.js:76:19)
 @ ./node_modules/css-loader!./node_modules/bootstrap/dist/css/bootstrap.css 6:4909-4961
 @ ./node_modules/bootstrap/dist/css/bootstrap.css
 @ ./public/js/app.js

ERROR in ./node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.svg
Module build failed: TypeError: Cannot read property 'fileLoader' of undefined
    at Object.module.exports (C:\Arma-WebAdmin\node_modules\file-loader\index.js:13:28)
    at Object.loader (C:\Arma-WebAdmin\node_modules\url-loader\dist\index.js:76:19)
 @ ./node_modules/css-loader!./node_modules/bootstrap/dist/css/bootstrap.css 6:4997-5049
 @ ./node_modules/bootstrap/dist/css/bootstrap.css
 @ ./public/js/app.js
i ｢wdm｣: Failed to compile.
Terminate batch job (Y/N)? y
PS C:\Arma-WebAdmin>
```

When I change the loaders on line 45 and 46 as well, then I'll see this error message:
```
PS C:\Arma-WebAdmin> npm start

> arma-server-web-admin@0.0.1 start C:\Arma-WebAdmin
> node app.js

C:\Arma-WebAdmin\node_modules\webpack\lib\webpack.js:23
                throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
                ^

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[1].rules[0] should be an object.
   -> A rule
    at webpack (C:\Arma-WebAdmin\node_modules\webpack\lib\webpack.js:23:9)
    at Object.<anonymous> (C:\Arma-WebAdmin\app.js:22:23)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)
    at startMainThreadExecution (internal/bootstrap/node.js:439:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! arma-server-web-admin@0.0.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the arma-server-web-admin@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-01-28T16_16_25_607Z-debug.log
PS C:\Arma-WebAdmin>
```
Am I doing something wrong? JSNode/npm is absolutely new ground for me. I am already happy to be able to update plugins/packs/whatever with `npm`. But I can't solve this. Let me know if you nee additional information.

**Comment by Dahlgren** [comment]
Which versions of packages are you running? The webpack versions declared in package.json is the older 1.x series to be compatible with older Node versions still shipped with Ubuntu LTS. `npm list` should spit out your package versions.

**Comment by Dahlgren** [comment]
@0xlord did you try with webpack 1.X?

That's the only currently supported version until I can drop support for Node <4 when Ubuntu 14.04 LTS ends in April.

**Comment by 0xlord** [comment]
Sorry, haven't found any time due RL. Webpack is >4.0.0 because I tried to fix it that way. I will deinstall JSNode and reinstall it again in hope that it will fix things. Is there an option to downgrade manually otherwise?

**Comment by Dahlgren** [comment]
If you do just `npm install` in the project directory it should install correct versions of all dependencies. Try removing the `node_modules` folder if you have one before the `npm install` to get a clean install

**Comment by chjo-hb** [comment]
I get this output when trying to run this app.
```
PS C:\armaserver> npm start

> arma-server-web-admin@0.0.1 start C:\armaserver
> node app.js

C:\armaserver\node_modules\webpack\lib\webpack.js:31
                throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
                ^

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'loaders'. These properties are valid:
   object { defaultRules?, exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, noParse?, rules?, strictExportPresence?, strictThisContextOnImports?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   -> Options affecting the normal modules (`NormalModuleFactory`).
    at webpack (C:\armaserver\node_modules\webpack\lib\webpack.js:31:9)
    at Object.<anonymous> (C:\armaserver\app.js:22:23)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! arma-server-web-admin@0.0.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the arma-server-web-admin@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chris\AppData\Roaming\npm-cache\_logs\2019-03-22T21_40_41_486Z-debug.log
PS C:\armaserver> npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 927 packages from 957 contributors and audited 6533 packages in 59.752s
found 5 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

More error messages,

```
PS C:\armaserver> npm start

> arma-server-web-admin@0.0.1 start C:\armaserver
> node app.js

C:\armaserver\node_modules\webpack\lib\webpack.js:31
                throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
                ^

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'loaders'. These properties are valid:
   object { defaultRules?, exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, noParse?, rules?, strictExportPresence?, strictThisContextOnImports?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   -> Options affecting the normal modules (`NormalModuleFactory`).
    at webpack (C:\armaserver\node_modules\webpack\lib\webpack.js:31:9)
    at Object.<anonymous> (C:\armaserver\app.js:22:23)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! arma-server-web-admin@0.0.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the arma-server-web-admin@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chris\AppData\Roaming\npm-cache\_logs\2019-03-22T21_45_58_809Z-debug.log
```
At the end it says,

```
npm ERR! peer dep missing: webpack@^1.0.0 || ^2.0.0 || ^3.0.0, required by webpack-dev-middleware@1.12.2
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.4.0
npm ERR! peer dep missing: ajv@>=5.0.0, required by ajv-errors@1.0.1
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.4.0
```

I am running Windows 10, with NodeJS v11.12 and it has webpack-dev-middleware@1.12.2 and webpack-sources@1.3.0

Not sure what's missing here.

**Comment by Dahlgren** [comment]
@chjo-hb

I tested just now with a clean install of Windows 10 and NodeJS 11.12 x64, worked just fine.

Your output from Webpack does not match the 1.x version of Webpack. Looks like your computer has a non supported newer version of webpack installed, 4.x would be my guess based on your first and last console log.

The only supported dependencies are those declared in the project, inside `package.json`. Those are installed using `npm install`. `npm list webpack` should list webpack as 1.15.0 and `npm list webpack --global` should say empty. `npm list` and `npm list --global` will output all installed modules.

Make sure you haven't modified `package.json`, delete the `node_modules` folder and execute `npm install` again.

**Comment by chjo-hb** [comment]
Thanks for a quick reply.  Thing is, I did do a clean install. But I'm going to try it again, and see if I can remove all nodejs references before installing again. I really like this approach over the TADST.
Will report back tomorrow with results. :)

**Comment by chjo-hb** [comment]
So, it turns out that Discord was the culprit. It also uses NodeJS for some of its features. I removed all of it and cleaned it out of my server computer. Reinstalled NodeJS and ran the npm install and start.

The only "error" messages I get now is,
```
npm WARN deprecated css-list@0.1.3: Deprecated.
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated postcss-single-charset@0.3.0: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated browserslist@0.4.0: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
```

But other than that, your application is now running fine. Now I only have to figure out a way to make it auto-start upon restarting the server. 

Thanks for making this great web app! Much appreciated!
Keep updating it, I will use it for years ahead. :)

**Comment by Dahlgren** [comment]
The warnings can be ignored, it's legacy modules to ensure it works with Node 0.10 on Ubuntu Trusty LTS.

If you install it as a service it will autostart with Windows in the background, https://github.com/Dahlgren/arma-server-web-admin#windows

**Comment by chjo-hb** [comment]
Ah, yes of course. Forgot about that one. :) 
Will use that then.

Thank you! :)
