### ISSUE TITLE
Virtual server node crashes when shutting down a server

### ISSUE THREAD

**Issue by Tirpitz93** [Dahlgren/arma-server-web-admin#183]
Testing the new virtual server version:

I get the following when I shut a server down.
Console output:

```
C:\arma-server-web-admin\lib\virtualServer.js:135
      cb(err)
      ^

TypeError: cb is not a function
    at C:\arma-server-web-admin\lib\virtualServer.js:135:7
    at CB (C:\arma-server-web-admin\node_modules\fs.extra\node_modules\rimraf\rimraf.js:68:5)
    at FSReqCallback.oncomplete (fs.js:146:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! arma-server-web-admin@0.0.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the arma-server-web-admin@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Tirpitz\AppData\Roaming\npm-cache\_logs\2021-03-05T09_06_04_290Z-debug.log
PS C:\arma-server-web-admin>

```
Log file:
```0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.14.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle arma-server-web-admin@0.0.1~prestart: arma-server-web-admin@0.0.1
6 info lifecycle arma-server-web-admin@0.0.1~start: arma-server-web-admin@0.0.1
7 verbose lifecycle arma-server-web-admin@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle arma-server-web-admin@0.0.1~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\arma-server-web-admin\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\PHP\v7.0;C:\Program Files\PHP\v7.2;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\Mercer\AppData\Local\Microsoft\WindowsApps;C:\Program Files\nodejs\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\webdrivers\chromedriver.exe;C:\Program Files (x86)\GnuWin32\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Azure Data Studio\bin;C:\Users\Tirpitz\AppData\Local\Microsoft\WindowsApps;
9 verbose lifecycle arma-server-web-admin@0.0.1~start: CWD: C:\arma-server-web-admin
10 silly lifecycle arma-server-web-admin@0.0.1~start: Args: [ '/d /s /c', 'node app.js' ]
11 silly lifecycle arma-server-web-admin@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle arma-server-web-admin@0.0.1~start: Failed to exec start script
13 verbose stack Error: arma-server-web-admin@0.0.1 start: `node app.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:223:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:223:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid arma-server-web-admin@0.0.1
15 verbose cwd C:\arma-server-web-admin
16 verbose Windows_NT 10.0.14393
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.14.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error arma-server-web-admin@0.0.1 start: `node app.js`
22 error Exit status 1
23 error Failed at the arma-server-web-admin@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by Dahlgren** [comment]
It's because the feature is not fully implemented yet

**Comment by Tirpitz93** [comment]
> It's because the feature is not fully implemented yet, branch is updated with fix
I am aware, I wanted to test it anyhow.
many thanks

**Comment by Dahlgren** [comment]
Thanks for reporting it!
