### ISSUE TITLE
Uncaught TypeError: Backbone.BootstrapModal is not a constructor

### ISSUE THREAD

**Issue by Shaquu** [Dahlgren/arma-server-web-admin#209]
Hi @Dahlgren 
I am trying to use the app on Windows 10.
When clicking add new server I get the error in the console:

```
Uncaught TypeError: Backbone.BootstrapModal is not a constructor
    at child.addServer (list.js:40:1)
    at executeBound (underscore-umd.js:986:1)
    at HTMLAnchorElement.<anonymous> (underscore-umd.js:1018:1)
    at HTMLAnchorElement.<anonymous> (underscore-umd.js:74:1)
    at HTMLDivElement.dispatch (jquery.js:5430:1)
    at HTMLDivElement.elemData.handle (jquery.js:5234:1)
```

**Comment by Dahlgren** [comment]
Hi @Shaquu 

It sounds like you're not using the correct package for the modal UI. Does your local copy have any changes to `package.json`?

You can try with a fresh set of dependencies by removing the `node_modules` folder, removing any `package-lock.json` file, restoring the `package.json` file and then run `npm install` again.

I've verified that the UI is working correctly on NodeJS 16.13.2.

**Comment by Shaquu** [comment]
I did removed node_modules and did fresh reinstall and nothing.
In the meantime I disabled error reporting in windows.
Then I have switched to steam workshop branch and it started to work.
