### ISSUE TITLE
Unexpected token =

### ISSUE THREAD

**Issue by PatRakowicz** [Dahlgren/arma-server-web-admin#239]
not sure whats happening, but i keep getting this run time error. I did npm install and fixed all dependencies. I am using the branch that provides mod workshop download.

If there is no hot fix for this i can just reinstall the package from github and redo all params.

```
> arma-server-web-admin@0.0.1 start /home/clt/A3-serverAdmin
> node app.js

/home/clt/A3-serverAdmin/node_modules/gamedig/lib/Results.js:2
    name = '';
         ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/clt/A3-serverAdmin/node_modules/gamedig/protocols/core.js:8:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! arma-server-web-admin@0.0.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the arma-server-web-admin@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

Log File
```
3 info using node@v10.24.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle arma-server-web-admin@0.0.1~prestart: arma-server-web-admin@0.0.1
6 info lifecycle arma-server-web-admin@0.0.1~start: arma-server-web-admin@0.0.1
7 verbose lifecycle arma-server-web-admin@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle arma-server-web-admin@0.0.1~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/clt/A3-serverAdmin/node_modules/.bin:/home/clt/.local/bin:/home/clt/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
9 verbose lifecycle arma-server-web-admin@0.0.1~start: CWD: /home/clt/A3-serverAdmin
10 silly lifecycle arma-server-web-admin@0.0.1~start: Args: [ '-c', 'node app.js' ]
11 silly lifecycle arma-server-web-admin@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle arma-server-web-admin@0.0.1~start: Failed to exec start script
13 verbose stack Error: arma-server-web-admin@0.0.1 start: `node app.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid arma-server-web-admin@0.0.1
15 verbose cwd /home/clt/A3-serverAdmin
16 verbose Linux 4.18.0-372.16.1.el8_6.0.1.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
19 verbose node v10.24.0
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error arma-server-web-admin@0.0.1 start: `node app.js`
22 error Exit status 1
23 error Failed at the arma-server-web-admin@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by Dahlgren** [comment]
What does `fixed all dependencies` mean? If you change the packages to other versions than the semver ranges specified it is very likely they will neither be compatible nor work with your nodejs version. Use the versions as specified in the repository.

**Comment by PatRakowicz** [comment]
ok will try, thanks

**Comment by PatRakowicz** [comment]
Fixed by reloading the package.json from the repo. Works just fine.
